version: '3'
services:
  webapp:
    container_name: "webapp"
    image: junalmeida/mono-web:latest
    build: ../
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./pools:/etc/mono/pools
      - ./app:/var/www/sample-app
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "400"
